### ISSUE TITLE
[Feature] Timer for the Night

### ISSUE THREAD

**Issue by freswa** [mudar/Fairphone#21] opened 2015-07-30 11:55 UTC
I know many of those "Task" Apps, which can do a lot depending on the clock. But they have so many confusing features. I only want to get disconnected from the digital world why I am resting or sleeping, so this apps seems to be suitable for me :).

What I would really like:
Add a scheduler for each day of the week for which one can use the disconnect feature automatically.

**Comment by fschwan** [comment] 2015-07-30 12:01
Sorry, duplicate of #17

**Closed** 2018-01-23 20:27 UTC
